version: '3.9'

services:
  app-back:
    container_name: app-back
    build: 
      context: .
      dockerfile: DockerFile.dev
    ports:
      - "3000:3000"
    links:
      - db-serve
    volumes:
      - .:/app
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db-serve
      - DB_PORT=3308
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=app-back
    depends_on:
      - db-serve
  db-serve:
    container_name: db-serve
    image: mysql:8.4.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app-back
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: